Bitbucket server
buildkite/docs pull request #1005
Opened 2021-04-15 09:43 UTC by StarfallProjects

2021-04-19 16:11 UTC, plaindocs reviewed
This is great progress! I've left a few suggestions and questions.

And I totally forgot  to mention this manual list as well. https://github.com/buildkite/docs/blob/a1ca405664baaca1eacbe04b2e45a70bba17a2c2/app/views/pages/index.html.erb#L28-L34

2021-04-19 16:11 UTC, plaindocs commented on pages/integrations/bitbucket.md.erb
> +This guide shows you how to set up your BitBucket builds with Buildkite.
Bitbucket or Bitbucket?

2021-04-19 16:11 UTC, plaindocs commented on pages/integrations/github_enterprise.md.erb
> +## Step 1: Register Buildkite as an OAuth App
Nice bunch of fixes to GitHub Enterprise. :+1:

2021-04-21 09:09 UTC, StarfallProjects commented on pages/integrations/bitbucket.md.erb
> +This guide shows you how to set up your BitBucket builds with Buildkite.
Fixed

2021-04-21 09:09 UTC, StarfallProjects commented on pages/integrations/bitbucket_server.md.erb
> +## Step 3: work through the in-app guide to set up your webhook
Added a few more "Bitbucket Servers" and a sentence to the step intro to clarify

2021-04-21 09:10 UTC, StarfallProjects commented on pages/integrations/bitbucket_server.md.erb
> +## Step 1: connect a repository provider and set up a pipeline
Fixed

2021-04-21 09:10 UTC, StarfallProjects commented on pages/integrations/bitbucket_server.md.erb
> +Buildkite integrates with Bitbucket Server to provide automated builds based on your source control. Your code pushes to BitBucket Server can automatically trigger Buildkite builds using a webhook.
Fixed

2021-04-21 09:12 UTC, StarfallProjects commented
@plaindocs all issues should now be fixed

2021-04-21 11:05 UTC, plaindocs requested changes
Couple more tiny changes.

2021-04-21 11:05 UTC, plaindocs commented on pages/integrations/bitbucket_server.md.erb
> +1. In your *Settings*, navigate to *Repository Providers*.
Style guide says we should not punctuate these.

2021-04-21 11:05 UTC, plaindocs commented on pages/integrations/bitbucket_server.md.erb
> +1. In your *Settings*, navigate to *Repository Providers*.
We should distinguish between person and org settings

![image](https://user-images.githubusercontent.com/95874/115543688-f348c900-a2a1-11eb-9432-70e9316107e0.png)

2021-04-21 14:28 UTC, plaindocs commented on pages/integrations/bitbucket_server.md.erb
> +4. In *URLs*, enter the address of your Bitbucket Server, including a port if needed. For example, `localhost:8000`. You also have the option to add *Allowed IP Addresses* in *Network Settings*.
```suggestion
4. In *URLs*, enter the address of your Bitbucket Server, including a port if needed. For example, `localhost:8000`. You can also restrict which network addresses are allowed to trigger builds via webhooks in  *Allowed IP Addresses* in *Network Settings*.
```

2021-04-21 14:29 UTC, plaindocs approved these changes
Looks good to me. This fixes https://github.com/buildkite/docs/issues/423 from Feb 2019!!!

2021-04-22 11:30 UTC, merged