Added GQL instructions for deleting org members
buildkite/docs pull request #1025
Opened 2021-04-30 07:20 UTC by karensawrey

2021-05-03 13:06 UTC, plaindocs requested changes
If you expand the breaking build in the linter, you can often see an indication of what isn't right:

![image](https://user-images.githubusercontent.com/95874/116879632-29326980-ac21-11eb-870f-565210cea748.png)

2021-05-03 13:06 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +Organization admin can delete orgranization members. To do it, the admin needs to:
Typo here (picked up by the linter).

2021-05-03 13:06 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +Organization admin can delete orgranization members. To do it, the admin needs to:
Also, we probably need to introduce the GraphQL element somehow. Maybe "To delete organization members using GraphQL, an organization admin needs to:" ?

2021-05-03 13:06 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +```bash
Probs needs a blank line, and the code isn't bash. `graphql` should work nicely.

2021-05-03 13:06 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +  2. Use the ID ("abc123") in a mutation:
And this is differently indented and not fenced.

2021-05-05 21:54 UTC, karensawrey commented
Oh my, such a small commit, so many issues %) Implemented all the fixes in one go. @plaindocs - please take a look

2021-05-17 14:28 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +Organization admin can delete organization members. To delete organization members using GraphQL, the admin needs to:
```suggestion
Organization admin can delete organization members. To delete organization members using GraphQL, the admin needs to:

```

2021-05-17 14:29 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +  1. Find the ID for the user to be deleted ("Jane Doe"):
```suggestion
1. Find the ID for the user to be deleted ("Jane Doe"):  
```

2021-05-17 14:29 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +  2. Use the ID ("abc123") in a mutation:
```suggestion
2. Use the ID ("abc123") in a mutation: 
```

2021-05-17 14:33 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +  2. Use the ID ("abc123") in a mutation:
Oh, I suspect this is going to cause issue with the numbering, we might need to indent the first code block to fix that.

2021-05-17 14:38 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +```
```suggestion
    ```graphql
    query {
    organization(slug: "your-organization-slug") {
        members(search: "Jane Doe", first: 10) {
        edges {
            node {
            role
            user {
                name
            }
            id
            }
        }
        }
    }
    }
    ```
```

2021-05-17 14:42 UTC, plaindocs commented on pages/pipelines/permissions.md.erb
> +```
```suggestion
1. Find the `id` for the user to be deleted (in this example `Jane Doe`):  

    ```graphql
    query {
    organization(slug: "your-organization-slug") {
        members(search: "Jane Doe", first: 10) {
        edges {
            node {
            role
            user {
                name
            }
            id
            }
        }
        }
    }
    }
    ```

2. Use the `id` from the previous query in a mutation: 

    ```graphql 
    mutation deleteOrgMember {
    organizationMemberDelete(input: { id: "abc123" }){
        organization{
        name
        }
        deletedOrganizationMemberID
        user{
            name
        }
    }
    }
    ```
```

2021-05-17 14:43 UTC, plaindocs approved these changes
Apologies for messing around with your PR so much.

2021-05-17 15:27 UTC, merged

2021-05-17 17:15 UTC, karensawrey commented
> Apologies for messing around with your PR so much.

Whatever it takes! :)