New environment variable data format and table
buildkite/docs pull request #1368
Opened 2022-02-10 09:56 UTC by plaindocs

2022-02-21 08:26 UTC, plaindocs commented
Example content:

```
null
"83d544ccc223c157d2bf80d3f2a32982c32c3c0db8e3674820da5064783fb091"
null
null
"10"
null
"experiment1,experiment2"
"localhost:8080"
"1a222222-e999-3636-8ddd-802222222222"
"\"BUILDKITE_AGENT_META_DATA_TAGNAME=tagvalue\", \"BUILDKITE_AGENT_META_DATA_QUEUE=some-queue\""
"elastic-builders-088264dc4f9"
"6"
"tmp/capybara/**/*;coverage/**/*"
"s3://name-of-your-s3-bucket/$BUILDKITE_PIPELINE_ID/$BUILDKITE_BUILD_ID/$BUILDKITE_JOB_ID"
"/usr/local/bin"
"master"
"/var/lib/buildkite-agent/builds/agent-1/pipeline-2"
"Carol Danvers"
"cdanvers@kree-net.com"
"Carol Danvers"
"cdanvers@kree-net.com"
"everyone:platform"
"4735ba57-80d0-46e2-8fa0-b28223a86586"
"1514"
"/var/lib/buildkite-agent/builds/"
"https://buildkite.com/acme-inc/my-project/builds/1514"
null
null
null
"script/buildkite/specs"
null
"-1"
"83a20ec058e2fb00e7fa4558c4c6e81e2dcf253d"
null
"/tmp/job-env-36711a2a-711a-484e-b180-e1b3711a80cf51b18711a"
"-ffxdq"
"-v"
null
"87972451"
"production"
"deploy"
"production"
"/etc/buildkite-agent/hooks/"
"BUILDKITE_GIT_CLEAN_FLAGS"
"e44f9784-e20e-4b93-a21d-f41fd5869db9"
":hammer: Specs"
"-1"
null
"Added a great new feature"
"acme-inc"
"0"
"5"
"main"
"my_project"
"github"
"my-project"
"[{\"github.com/buildkite-plugins/docker-buildkite-plugin#v3.7.0\":{\"image\":\"node:lts-alpine3.14\"}}]"
null
"/etc/buildkite-agent/plugins/"
null
"'123' for pull request #123, or 'false' if not a pull request"
"'main', or '' if not a pull request"
"'git://github.com/acme-inc/my-project.git', or '' if not a pull request"
"'4735ba57-80d0-46e2-8fa0-b28223a86586', or '' if not a rebuild"
"'1514', or '' if not a rebuild"
"+refs/weird/123abc:refs/local/weird/456"
"git@github.com:acme-inc/my-project.git"
"/tmp/buildkite-git-mirrors"
"0"
"AKIAIOSFODNN7EXAMPLE"
"https://buildkite-artifacts.example.com/"
null
null
"wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
null
"/bin/bash -e -c"
null
null
"080b7d73-986d-4a39-a510-b34f9faf4710"
"tests-06"
"v1.2.3"
"'15' for 15 minutes, or 'false' if no timeout is set"
"datadog"
"'5aa7c894-c8c0-435b-bc17-13923b90f163', or ''' if the build was not triggered from another build"
"'1264', or '' if the build was not triggered from another build"
"'build-and-test', or '' if the build was not triggered from another build"
"Carol Danvers"
"carol@nasa.gov"
"4735ba57-80d0-46e2-8fa0-b28223a86586"
"everyone:platform"
null
```

2022-03-01 04:20 UTC, lachlanhardy commented
<img width="809" alt="image" src="https://user-images.githubusercontent.com/3682/156104193-9939fdfd-f047-4e62-9bfc-1cc1bd56e083.png">

New design in. And test fixed!

2022-03-03 11:26 UTC, plaindocs commented
I'll have to integrate https://github.com/buildkite/docs/pull/1403 before we merge this.

2022-03-04 04:19 UTC, lachlanhardy commented
Added `example` and styled them

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/3682/156698631-4032d788-0256-4618-ad8a-d58ce20e9d9a.png">

2022-03-10 02:40 UTC, lachlanhardy commented
@plaindocs Lemme know if I can help with that integration. Otherwise, this one is all yours.

2022-03-10 08:54 UTC, plaindocs commented
Yep, conflict and update totes on my plate. But my plate, it overfloweth.

2022-03-10 14:40 UTC, plaindocs commented on data/environment_variables.yaml
> +  example: "/etc/buildkite-agent/plugins/"
```suggestion
  example: "`"/etc/buildkite-agent/plugins/"`"
```

2022-03-10 14:41 UTC, plaindocs commented on data/environment_variables.yaml
> +  example: "'4735ba57-80d0-46e2-8fa0-b28223a86586', or '' if not a rebuild"
```suggestion
  example: "`"4735ba57-80d0-46e2-8fa0-b28223a86586"`, or `""` if not a rebuild"
```

2022-04-15 17:06 UTC, karensawrey commented on pages/pipelines/environment_variables.md.erb
> +=======
```suggestion

```

2022-04-15 17:08 UTC, karensawrey requested changes
L53 bothers me with that "TODO" + there was 2 merge commits that I resolved & I need a 2nd pair of eyes to take a look at the results. @plaindocs

2022-04-21 14:52 UTC, plaindocs reviewed
This has been quite the journey. Let's merge it quick before anything else changes.

2022-04-22 09:22 UTC, karensawrey approved these changes

2022-04-22 09:22 UTC, merged