Improve hooks table visualisation
buildkite/docs pull request #1489
Opened 2022-05-11 04:42 UTC by olyism

Added design improvements to better communicate job lifecycle hooks.

The [current table](http://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks) doesn't provide an obvious visual representation of the order of hook execution.

🎦 Here's a Loom recording of me going through the changes https://www.loom.com/share/92f99e8ea1e7419c86ac835a6c92773a

Visual design improvements:
- Placed Location Orders in a vertical manner to visualise order
- Append colored icons to help readers to visually differentiate between the different locations
- Split Plugin into non-vendored and vendored for better clarity

Other improvements:
- Improvement maintainability: refactored existing table from html to markdown
- Re-skinned the [agent lifecycle hooks table](http://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks) with the same style

# Before

<img width="651" alt="Screen Shot 2022-05-11 at 2 34 00 pm" src="https://user-images.githubusercontent.com/7202667/167769811-6da08a61-dec7-42e2-8b82-85e6489496c8.png">

# After

<img width="659" alt="Screen Shot 2022-05-11 at 2 29 20 pm" src="https://user-images.githubusercontent.com/7202667/167769379-798ec539-a85e-42e5-b4e2-61a13b954a2a.png">

2022-05-11 04:44 UTC, olyism commented
Oops. Looks like I have some linting errors to fix. Will work on that.

2022-05-11 06:46 UTC, plaindocs commented
I took the liberty of jumping in to your PR to kick the linter.

2022-05-11 12:08 UTC, plaindocs approved these changes
Love this work, huge improvement.

2022-05-12 18:42 UTC, pzeballos requested changes
Just a bit clarification, but the rest looks good!

2022-05-12 18:42 UTC, pzeballos commented on pages/agent/v3/hooks.md.erb
> +from GitHub), which affects the order they are run in.
It's not exclusive of Github, non-vendored can be hosted on others repository providers

2022-05-12 19:03 UTC, plaindocs commented on pages/agent/v3/hooks.md.erb
> +from GitHub), which affects the order they are run in.
```suggestion
from elsewhere), which affects the order they are run in.
```

2022-05-16 09:12 UTC, karensawrey commented on pages/agent/v3/hooks.md.erb
> +them. Plugins can be *vendored* (if they are already present in the repository,
Clarified. All clear.

2022-05-16 09:13 UTC, karensawrey requested changes

2022-05-16 09:13 UTC, karensawrey commented on styleguide/STYLE.md
> +You can prepend an icon to boost the visual emphasis for an inline text. To do this, simply wrap the text with `<span class="add-icon-#{ICON_NAME}">`.
```suggestion
You can prepend an icon to boost the visual emphasis for an inline text. To do this, wrap the text with `<span class="add-icon-#{ICON_NAME}">`. 
```

2022-05-16 09:13 UTC, karensawrey commented on styleguide/STYLE.md
> +At the time of writing there are only three icons available — agent, repository and plugin. To add more icons see `$icons` in `_add-icon.scss`, add a new name as the key and the inline SVG. Icon dime
```suggestion
At the time of writing there are only three icons available — agent, repository, and plugin. To add more icons see `$icons` in `_add-icon.scss`, add a new name as the key and the inline SVG. Icon dimension must be 22px * 22px.
```

2022-05-17 10:10 UTC, karensawrey commented
> @olyism I reckon we can address Karen's concerns and get this merged in, what do you reckon?

Let's correct & :shipit:

2022-05-17 23:37 UTC, olyism commented
:shipit:

2022-05-17 23:37 UTC, merged