Add detailed style guidance for writing about YAML
buildkite/docs pull request #1518
Opened 2022-05-20 16:37 UTC by ddbeck

YAML is a little bit of a nightmare: You studied! You should know this! But you're late for the exam! 😱

If there's one thing I want to communicate it is this: don't talk about YAML qua YAML if you can avoid it. As much as possible, talk about the things it does for the reader—creating pipelines, modifying behavior—not the act of authoring YAML.

To come up with this stuff, I looked at what the YAML specification uses and what the existing docs do and what some other documentation that mentions YAML does. This is what I came up with, in attempt to (mostly) capture the most common usage in the Buildkite docs already and make some useful distinctions, where there are conflicts in the existing text (of which there are many).

2022-05-23 16:11 UTC, karensawrey requested changes
Great addition! Needs a few tiny tweaks before we merge it.

2022-05-23 16:11 UTC, karensawrey commented on styleguide/yaml.md
> +# Talking about YAML
```suggestion
# Talking about YAML

This document is a part of the larger [style guide](./STYLE.md) and it covers the usage of YAML in the Buildkite documentation. Further expansion of this guide is highly welcomed.
```

2022-05-24 17:44 UTC, karensawrey approved these changes
Looks good!

2022-05-24 18:01 UTC, ddbeck commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
Oh wait, I forgot to address this!

So, I kinda-sorta covered this in the earlier maps section, like so:

> If you must describe a map within a map or other structure, qualify the relationship with *of* or use the term *nested map*. Do not use the terms *block*, *level*, or the prefix *sub*.

My instinct here was to discourage using "levels" to describe the relationship between nested maps. The vertical level metaphor works pretty well with the block-style notation, but not so much with the flow-style notation (e.g., given `{ a: { b: false } }`, `b` lacks any visual leveliness, for lack of a better word). And it falls apart quickly when you involve arrays (is a map in an array in a map second or third level?).

That said, I could write an exception for the top-level map. However, I think it's avoidable entirely (calling back to the "refer to what the YAML represents" directive at the outset), so maybe we could see whether we can get away without it?

2022-05-27 12:29 UTC, karensawrey commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
I must confess that the more I read the proposed improvement regarding the block vs flow-style notation, the more confusing it gets.

2022-05-27 14:22 UTC, ddbeck commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
It _is_ confusing. I spent a bit of time reading the YAML spec, so I've got a long head starting thinking about how to talk about YAML. But fundamentally, the problem is this: YAML has lots of ways to record the same data (e.g., inline versus block, quoted versus unquoted, etc.) and it's very easy to overdetermine what we're asking for.

Consider this YAML source:

```yaml
meal:
  type: sandwich
  size: small
  vegan: false
```

It's directly equivalent to this YAML source:

```yaml
{ meal: { type: "sandwich", size: "small", vegan: FALSE } }
```

`meal` is a "top-level" map in both, but in the latter case the top-level map is metaphorical, as there's no visual vertical hierarchy depicted by the source. What we really care about is that readers use the right structure and values, not the specific notation that we prescribe.

2022-05-27 15:54 UTC, karensawrey commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
After giving this more thought... I think we'd be better off merging the addition to the style guide vs trying to come up with a perfect way to address map/levels and never merging it ;) So please finalize the PR as you see fit in that regard. 🙏  I'm very much OK with the rest of the PR I've already reviewed. 👍

2022-06-02 16:21 UTC, plaindocs commented
I'll dig into this when I get back, looks like thorough work.

2022-07-21 15:10 UTC, plaindocs approved these changes
This is great. 

How about we add a _Buildkitey_ example of Map, Attribute, Key and value and Array, and merge this in.

Thanks for your patience @ddbeck

2022-07-21 15:10 UTC, plaindocs commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
I've **finally** made it here.  

I think we can focus exclusively on the more human-readable line-break and whitespaced YAML, if you'll permit

:heavy_check_mark:  

```yaml
meal: 
  type: sandwich 
  size: small 
  vegan: false
```

❌

```yaml
{ meal: { type: "sandwich", size: "small", vegan: FALSE } }
```

And I think we can **probably** ignore the indenting and trust the linter (which we don't yet have for codeblocks) to sort that out.

2022-07-26 12:35 UTC, ddbeck commented on styleguide/yaml.md
> +❌ Add the skip key to the command step, then on a new line…
Cool, I've added this as a general guideline, closer to the top. I also added a bit more structure to the whole thing, so it's easier to ignore the bits that won't apply in the usual course of events.

2022-07-26 12:38 UTC, merged

2022-07-26 12:46 UTC, plaindocs commented
Sorry @ddbeck one more change (addition now), which I did not communicate well.

I'd love to see a YAML example in each of the H3 headings inside `## Terms`, ie, this is what a YAML array looks like, this is what a YAML map looks like. And I'd love to see that using examples from the docs or similar, not sandwich types. (although I love Sandwiches)

Thanks for tackling this guide!