✨ New Test Analytics landing page layout
buildkite/docs pull request #1523
Opened 2022-05-24 14:15 UTC by olyism

# New Test Analytics landing page layout

Build as per the [design](https://www.figma.com/file/g8o1YHBrhbGr9FI3ZGoatP/Project%3A-Docs-Test-Analytics-Jun-launch?node-id=45%3A288), with content matching what we currently have available.

## New features

- New layout
- Move features content on the overview landing page to a new features page
- Ability to set a page to `is_landing_page`, which removes the right column and increase the main body width
- New Tiles layout
  - Use `data/tiles.yml` to manage Tiles content
  - Insert Tiles with `<%= tiles "tiles_name" %>`
- New button partial

## Screenshot

<img width="480" alt="Screen Shot 2022-05-25 at 12 09 47 am" src="https://user-images.githubusercontent.com/7202667/170056079-d0f411a7-6b0e-446e-92f7-8bf261ea59aa.png">

Also, very green to Ruby on Rails, so hopefully the code is ok 🙇‍♂️

2022-05-25 12:32 UTC, karensawrey commented
After a conversation with @olyism, this is still a WIP, reviews are to be put on hold. 
Pre-agreed todo:
- Return the info on the number of monitors.
- Offload the style guide-related stuff to a separate PR.

2022-05-26 01:52 UTC, olyism commented
Added a new 🎦 Loom as the PR is quite big. Hope this short video helps https://www.loom.com/share/b5e385f8fc0949b8b649ff62426a6cd8

2022-05-27 15:15 UTC, karensawrey requested changes

2022-05-27 15:42 UTC, karensawrey commented
So this is what I'm suggesting. If you hate it, feel free to revert my last commit :) 
![moved-the-button-around](https://user-images.githubusercontent.com/27306876/170733117-fa35e4da-e874-4a38-83d4-abe9dc07faa4.png)

2022-05-27 15:42 UTC, karensawrey approved these changes

2022-05-29 10:49 UTC, merged