WIP: Expand TA feature information in docs, and add subsections to left nav
buildkite/docs pull request #1532
Opened 2022-05-29 04:56 UTC by meiqimichelle

🚧 🚧 WIP 🚧 🚧 (not ready for review)

This PR creates separate pages for Test Analytics feature information so we can provide more detail into what we now know are commonly-asked questions. It also lays the groundwork for a future PR to pull env var info into its own section. //cc @ddbeck

NB: This is branched off of the new landing page work in https://github.com/buildkite/docs/pull/1523 because my brain couldn't handle thinking about this re-org without the new landing page in place. //cc @olyism @karensawrey

2022-05-29 10:47 UTC, olyism requested changes
Thanks @meiqimichelle for putting the extra pages together. 

The build has failed on a missing section/anchor link on the homepage as the ["flaky test" heading](https://github.com/buildkite/docs/pull/1532/files#diff-61970285059c3fc9b5fe2d5b51fe729898101c7a0b3bbefff60f909badf10ed5R41) has changed. [Please view suggestion](https://github.com/buildkite/docs/pull/1532/files#diff-61970285059c3fc9b5fe2d5b51fe729898101c7a0b3bbefff60f909badf10ed5R41).

2022-05-29 10:47 UTC, olyism commented on app/views/pages/index.html.erb
> +          <li><%= link_to "Find and fix flaky tests", "/docs/test-analytics/features#find-flaky-tests" %></li>
```suggestion
          <li><%= link_to "Find and fix flaky tests", "/docs/test-analytics/features#find-flaky-unreliable-tests" %></li>
```

🚨 Fix test for broken section/anchor link, as the heading has been changed on `/test-analytics/features`

2022-05-30 01:15 UTC, olyism commented
Thanks @meiqimichelle for putting the content together 🙌

I've got some thoughts on the design layout/visual styling, but as the PR is getting quite big so I'll raise a separate PR for design improvements.

2022-05-30 18:23 UTC, plaindocs commented
Thanks for putting this together @meiqimichelle, there is a bunch of great stuff. Take a look at b330ece and see if it all makes sense to you? 

Environment variables refactor is now happening in #1536, it'll add a CI Environments page (which also needs adding to `beta_pages.rb` @ddbeck 

I don't love the feature page, as a mix of description of what it does, but I'm not sure of an alternative right now. 
I also don't love a ton of "Coming soon" sections, but as long as we make sure we do deliver those, and definitely don't give time estimates, it's hopefully useful info to some folks.

2022-05-30 18:28 UTC, plaindocs commented on pages/test_analytics/features.md.erb
> +For example, in the following example, you can see that the test execution duration of 5.26 seconds is 2 seconds and 233 milliseconds more than the median of the previous 25 executions. In addition,
```suggestion
For example, in the following screenshot, you can see that the test execution duration of 5.26 seconds is 2 seconds and 233 milliseconds more than the median of the previous 25 executions. In addition, the current value for this test execution of 5.26 seconds is in the 66th percentile within the distribution over the last 25 executions.
```

2022-05-31 00:46 UTC, meiqimichelle commented
@plaindocs love your edits, thank you!

Agree on the "it's a bit odd to shove all this info into a page called 'Features'" -- it is a bit of a grab bag that has leftover vibes from when these docs were quite marketing-heavy. Maybe a refactor will become obvious once these changes are out the door.

I also don't love the 'coming soon' sections. The main one I'd like to tell people about (and I think why I started even writing 'coming soon' in the first place) was the bit about being able to URL hack other branch views into Test Analytics (even though you can only select 'all branches' or your default branch in the UI). The others aren't really as vital in terms of how to use the thing. 🤔 Should we just remove all of those sections for now?

2022-05-31 00:56 UTC, meiqimichelle commented
Ugh. I'm re-reading, and comparing to our approach in other sections. It just doesn't match. This may be the best we can do for a first go -- but my goodness. I'm going to have a quick go based on your changes to move us further away from 'marketing' and more towards 'this is how you use the thing' -- I think that will help better align with the rest of our docs.

2022-05-31 01:23 UTC, meiqimichelle commented
@plaindocs have a look at my refactor -- I didn't change the `_sidebar` file yet, but in this scenario I'd suggest re-naming that to 'Configure Test Suites' or somesuch.

2022-05-31 11:16 UTC, plaindocs commented
@meiqimichelle love your work! I've edits the edits a nudge, done the sidebar work. Expecting these tests to pass. ;-)

2022-05-31 11:29 UTC, plaindocs commented
I propose merging this, and starting any new edits in a new PR. 

(Incidentally we now have to edit a **bunch** of places when we change file or section names, I should probably write this up as a post, cos it's not gonna scale I don't think)

2022-05-31 11:30 UTC, plaindocs approved these changes
Good enough?

2022-05-31 23:25 UTC, olyism approved these changes

2022-05-31 23:26 UTC, olyism commented
LGTM, any design tweaks can come in another PR so won't hold up the docs content

2022-05-31 23:40 UTC, meiqimichelle commented
Awesome! Thanks for the further edits @plaindocs -- merging so that we're ready with any further improvements in another PR! 🚀

2022-05-31 23:40 UTC, merged