📝 Add TA roadmap page
buildkite/docs pull request #1592
Opened 2022-06-15 04:06 UTC by olyism

Add Test Analytics roadmap page.

![image](https://user-images.githubusercontent.com/7202667/173734670-98bbdab5-e1e6-4acd-9975-db5cb93b8d2c.png)

2022-06-15 10:56 UTC, plaindocs approved these changes
This works for me. Can we set up a recurring Linear ticket to update it every X weeks @meiqimichelle ?

2022-06-15 11:01 UTC, karensawrey requested changes
Great job! A few improvements in the review. I'm pretty sure, @plaindocs will be able to make some things even more breve and clear after these are imlemented.

2022-06-16 00:09 UTC, olyism commented on pages/test_analytics/roadmap.md.erb
> +We've got a pretty good idea of the work required for these items, and we'll be prototyping these soon:
```suggestion
We've got plans for many exciting new things, and these are the ones we'll be prototyping soon:
```

2022-06-16 00:11 UTC, olyism commented on pages/test_analytics/roadmap.md.erb
> +- More ways to organise and group your tests — by namespace, filename or team, for example — so you can quickly find the patterns and data you need
```suggestion
- More ways to organize and group your tests — by namespace, filename, or team. For example — to quickly find the patterns and data you need.
```

2022-06-16 00:14 UTC, olyism commented
hi @meiqimichelle I've added some very minor text suggestions. Passing the ball over to you ⚽️ to take a look to commit the suggestions or make other changes.

2022-06-16 10:12 UTC, karensawrey commented
(CC: @olyism) @meiqimichelle I'm changing my review status to Approved - please look at my suggestions & merge the ones you agree with. Then let's get this rollin'!

2022-06-16 10:13 UTC, karensawrey approved these changes
Do merge after committing the suggested changes.

2022-06-28 11:14 UTC, meiqimichelle commented
@olyism I've pulled this down to take a look -- apologies it's taken me so long to confirm. I'll push a few minor edits up while I'm here, but I want to confirm this list with the team this week before making public. Merging won't push out longer than end of this week or early next, I'm sure of it!

2022-06-28 11:24 UTC, meiqimichelle commented
Also, I can't figure out why this particular dot point isn't parsing the line break/paragraph break. Womp womp.
<img width="563" alt="Screen Shot 2022-06-28 at 9 21 27 PM" src="https://user-images.githubusercontent.com/4827522/176166952-f5d60a86-e93e-43ae-9583-311147c3f0b9.png">

2022-06-28 13:17 UTC, plaindocs commented
@meiqimichelle you **do** want the line break? or you don't? Either way, you're doing stuff that markdown doesn't really encourage. There is no concept of definition list. 

I've fixed it for what I think you want.

2022-06-28 13:22 UTC, olyism commented
Too quick @plaindocs ⚡️ I was looking at the same thing. @meiqimichelle you can use double space for line breaks in bullet points.

No worries about the time. I was just checking in :) Drop me a line when it's ready to go and I can help you rebase the branch to pull in the recent nav changes.

2022-06-29 08:02 UTC, meiqimichelle commented
(I don't have a strong opinion about the line break -- I was just trying to get it to match the others in the design)

2022-07-13 13:24 UTC, karensawrey commented
@meiqimichelle @olyism where are we with this one?

2022-07-18 10:34 UTC, plaindocs commented
@olyism what do you think about having a distinct page layout for roadmaps, to highlight the fact that these aren't "solid docs"?

2022-07-19 03:16 UTC, olyism commented
hi @plaindocs yes, keen to have a different page layout for Roadmaps. I've got a backlog ticket to provide a different design for it, which I haven't had a chance to start yet.

Question to everyone — are we okay to scope this PR to use the standard template for the release? If we're waiting for the design we might be delayed a bit.

2022-07-20 10:00 UTC, plaindocs commented
There doesn't appear to be much action here, but regardless I'm happy to merge this first and iterate on the design after.

2022-11-09 05:54 UTC, olyism commented
hi @meiqimichelle I'm pruning the PRs and issue in Docs' GitHub repo. Can you confirm if we still want to have TA roadmap on Docs, or can we de-prioritise and cancel this PR and look into next year when we start to look at a proper roadmap solution.

2022-11-09 07:06 UTC, meiqimichelle commented
Uff. This PR is quite stale at this point, hey? I can always re-create, if needed. Feel free to close this one for now.

2022-11-09 22:43 UTC, closed without merging

2022-11-09 22:44 UTC, olyism commented
Thanks @meiqimichelle :) closing this PR for now. Let's chat about public-facing roadmaps when we reboot it in the next quarter.