Adding access level parameter for pipeline create REST API info
buildkite/docs pull request #1604
Opened 2022-06-22 15:36 UTC by karensawrey

This PR adds the info about `teams` parameter that replaces the deprecated `team_uuids` parameter.

2022-06-23 11:34 UTC, olyism requested changes

2022-06-23 11:41 UTC, karensawrey commented
Thank you so much for the help, @olyism!
Now I need to get rid of the trailing " in there, but it already looks the way it's supposed to.

2022-06-23 13:58 UTC, pzeballos requested changes
It's not clear to me a sentence, but the rest looks good 👍🏻

2022-06-23 13:58 UTC, pzeballos commented on pages/apis/rest_api/pipelines.md.erb
> +    <td>An array of team UUIDs to add this pipeline to. Allows you to very access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read
```suggestion
    <td>An array of team UUIDs to add this pipeline to. Allows you to specify the access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read</code>, and <code>manage_build_and_read</code> You can find your team's UUID either using the <a href="/docs/apis/graphql-api">GraphQL API</a>, or on the settings page for a team. This property is only available if your organization has enabled Teams. Replaces deprecated <code>team_uuids</code> parameter.<p class="Docs__api-param-eg"><em>Example:</em>
```

2022-06-23 13:58 UTC, pzeballos commented on pages/apis/rest_api/pipelines.md.erb
> +    <td>An array of team UUIDs to add this pipeline to. Allows you to very access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read
Not sure I get the `very` on this line, I updated a bit the text

2022-06-23 13:58 UTC, pzeballos commented on pages/apis/rest_api/pipelines.md.erb
> +    <td>An array of team UUIDs to add this pipeline to. Allows you to very access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read
```suggestion
    <td>An array of team UUIDs to add this pipeline to. Allows you to specify the access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read</code>, and <code>manage_build_and_read</code> You can find your team's UUID either using the <a href="/docs/apis/graphql-api">GraphQL API</a>, or on the settings page for a team. This property is only available if your organization has enabled Teams. Replaces deprecated <code>team_uuids</code> parameter.<p class="Docs__api-param-eg"><em>Example:</em>
```

2022-06-23 13:58 UTC, pzeballos commented on pages/apis/rest_api/pipelines.md.erb
> +    <td>An array of team UUIDs to add this pipeline to. Allows you to very access level for the pipeline in a team. The available access level options are <code>read_only</code>, <code>build_and_read
Same here

2022-06-23 15:38 UTC, karensawrey commented
@pzeballos yeah, that "very" was supposed to be "specify" - some rogue autocorrect at work, sorry. Thanks for catching it!

2022-06-23 15:49 UTC, pzeballos approved these changes

2022-06-24 12:07 UTC, karensawrey commented
Let's get this one rollin`.

2022-06-24 12:07 UTC, merged