Markdown compatible notes
buildkite/docs pull request #1744
Opened 2022-10-17 09:50 UTC by lachlanhardy

This resolves ONB-59: https://linear.app/buildkite/issue/ONB-59/markdown-compatible-notes

2022-10-18 10:50 UTC, olyism requested changes
hi @lachlanhardy looks really good. I learned several Ruby chops here 🧠 ✨ 

I've made two small nitpicking requests. Let me know what you think. Thanks :)

2022-10-24 13:50 UTC, lachlanhardy commented on app/assets/stylesheets/public/_callout.scss
> +.callout {
Good call. I think I prefer this.

2022-10-24 22:18 UTC, olyism approved these changes

2022-10-24 22:18 UTC, olyism commented
Thanks @lachlanhardy for the fixes, LGTM 🚀

2022-10-25 02:27 UTC, merged