WIP: Add android collector to docs
buildkite/docs pull request #1763
Opened 2022-11-03 05:23 UTC by meiqimichelle

We've had an Android test collector for ages, but have not updated our public docs. We should fix that.

This PR:
- [x] Creates a new page to house information about our Android collector
- [x] Copy-pasta docs from the [collector readme](https://github.com/buildkite/test-collector-android/blob/main/README.md)
- [ ] Deletes Android from the 'coming soon' page

2022-11-03 05:38 UTC, meiqimichelle commented
Hello, @olyism ! I guess you're on deck for reviews at the moment?

This is a v quick PR, apologies -- please have a look locally. I did this the fast and dirty way (ie, in-browser edits) and have not confirmed that everything is working properly. I have another PR coming soon (.NET) so will see about pulling down properly tomorrow, if you don't get to it first. 🙇🏻‍♀️

2022-11-03 07:08 UTC, olyism commented
hi @meiqimichelle, all good, I'll take a look :)

2022-11-03 23:53 UTC, meiqimichelle commented
I had a moment this morning to pull down and 👀. I think everything is working the way it should. Over to you @olyism .

2022-11-10 11:03 UTC, olyism requested changes
Hi @meiqimichelle thanks for putting this PR together. Please see requested changes: 

1. Minor suggestion to add beta pill to Swift
2. Remove footer text that was unintentionally pasted in

Thanks :)

2022-11-10 11:03 UTC, olyism commented on pages/test_analytics/android_collectors.md
> +About
Please remove footer text from GitHub 🔥 

```suggestion
```

2022-11-10 11:08 UTC, olyism commented
> Hello, @olyism ! I guess you're on deck for reviews at the moment?

Hi @meiqimichelle, apologies for the late reply. Yes, it's mostly just me on deck for reviews 😓 

> This is a v quick PR, apologies -- please have a look locally. I did this the fast and dirty way (ie, in-browser edits) and have not confirmed that everything is working properly. I have another PR coming soon (.NET) so will see about pulling down properly tomorrow, if you don't get to it first. 🙇🏻‍♀️

We have Render preview (see https://github.com/buildkite/docs/pull/1763#issuecomment-1301651974 top of this page) to test with :)

2022-11-14 07:08 UTC, meiqimichelle commented
Thanks @olyism ! I believe I accepted all your changes. Just waiting for the preview to build to 👀 but happy for you to merge if you 👀 and everything looks good 💚

2022-11-16 02:55 UTC, olyism commented
Resolved conflict in 756fb76040b5bee06f9f7509de135f5e64a76114

2022-11-16 03:05 UTC, olyism approved these changes
Checked code and preview site. LGTM ✅  Ready for merge 🚀

2022-11-16 03:25 UTC, merged