Update pipelines.md
buildkite/docs pull request #2463
Opened 2023-09-06 22:19 UTC by stephanieatte

Some provider settings where missing from the docs as per https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline#provider-settings-configuration

I added in the Properties available for Bitbucket Cloud, GitHub, and GitHub Enterprise: optional properties
build_branches                              build_pull_request_labels_changed  
cancel_deleted_branch_builds    
       
Additional properties available for GitHub:
 build_pull_request_ready_for_review

2023-09-13 00:22 UTC, dannymidnight requested changes
Looks good, just some minor suggestions for consistent punctuation. 

(not blocking) This PR makes me wonder if we should think about deriving out rest API docs from the terraform provider schema 🤔

2023-09-13 00:22 UTC, dannymidnight commented on pages/apis/rest_api/pipelines.md
> +      Whether to create builds when branches are pushed
```suggestion
      Whether to create builds when branches are pushed.
```

2023-09-13 00:22 UTC, dannymidnight commented on pages/apis/rest_api/pipelines.md
> +      A boolean to enable automatically cancelling any running builds for a branch if the branch is deleted
```suggestion
      A boolean to enable automatically cancelling any running builds for a branch if the branch is deleted.
```

2023-09-13 00:22 UTC, dannymidnight commented on pages/apis/rest_api/pipelines.md
> +        Whether to create builds for pull requests when labels are added or removed
```suggestion
        Whether to create builds for pull requests when labels are added or removed.
```

2024-04-23 01:30 UTC, gilesgas approved these changes

2024-04-23 01:52 UTC, merged