Agent 3.66
buildkite/docs pull request #2710
Opened 2024-03-12 03:55 UTC by moskyb

This PR does two things:
- Updates the CLI reference to be generated from the latest version of the agent (the first commit)
- Adds new CLI reference entries for the recently-added `secret get` and `redactor add` commands

Note that if you have comments on the wording in generated files, i can't change them here, and we should work on submitting a PR to the agent to clear up wording there.

2024-03-12 03:59 UTC, triarius approved these changes
LGTM. I think we need to change our processes so that the person who made these changes (me) is prompted to add these, not the person who happens to be releasing the agent. Perhaps we should add a section to the PR template?

2024-03-12 04:28 UTC, moskyb commented
@triarius good call - will add something to the agent PR template

2024-03-14 22:14 UTC, gilesgas commented on pages/agent/v3/cli_secret.md
> +> Note: The `secrets` command, as well as its associated server-side features, are currently in feature preview. If you're interested in trialing Buildkite Secrets, [contact support](mailto:support@b
Thanks very much for your contribution @moskyb !

For consistency with the rest of the Buildkite Docs, I'd recommend sticking to our existing [style guide for callouts/admonitions](https://github.com/buildkite/docs/blob/main/styleguides/markdown-syntax-style.md#callouts):

```suggestion
> 📘 The `secrets` command, as well as its associated server-side features, are currently in feature preview.
> If you're interested in trialing Buildkite Secrets, [contact support](mailto:support@buildkite.com).
```

2024-03-14 22:15 UTC, gilesgas requested changes
Just one more comment (mine) to address ^

2024-03-14 23:45 UTC, gilesgas approved these changes

2024-03-14 23:49 UTC, merged

2024-03-14 23:49 UTC, gilesgas commented on pages/agent/v3/cli_redactor.md
> +However, sometimes a job will source something sensitive through a side channel - perhaps a third-party secrets storage system like Hashicorp Vault or AWS Secrets Manager. In these cases, you can use
One last thing, we're adopting Google's developer documentation guidance on using [em dashes to represent pauses in text like this (deliberately without spacing)](https://developers.google.com/style/dashes):

```suggestion
However, sometimes a job will source something sensitive through a side channel—perhaps a third-party secrets storage system like Hashicorp Vault or AWS Secrets Manager. In these cases, you can use the `redactor add` command to add the sensitive information to the redactor, ensuring it is redacted from subsequent logs.
```

Would be nice to commit this before merging :-)

2024-03-14 23:50 UTC, moskyb commented on pages/agent/v3/cli_redactor.md
> +However, sometimes a job will source something sensitive through a side channel - perhaps a third-party secrets storage system like Hashicorp Vault or AWS Secrets Manager. In these cases, you can use
ah shit, just barely too slow 😅

2024-03-14 23:50 UTC, gilesgas commented on pages/agent/v3/cli_redactor.md
> +However, sometimes a job will source something sensitive through a side channel - perhaps a third-party secrets storage system like Hashicorp Vault or AWS Secrets Manager. In these cases, you can use
Whoops, too late—my bad lol (another time)