SUP-2217: highlight block and input steps cannot be used within concurrency gates
buildkite/docs pull request #2799
Opened 2024-05-15 13:20 UTC by tomowatt

We had user mention this information is not emphasied enough as it is a short line added to the end of the paragraph and easily missed resulting in errors when using concurrency gates, so moving it into its own block to highlight it.

2024-05-15 13:32 UTC, pzeballos commented
@gilesgas this is the same as #2620

2024-05-17 00:03 UTC, gilesgas commented
Thanks @tomowatt and @pzeballos , I will rework the wording and implementation of this new note now that we have the new troubleshooting note above it in the previous section.

2024-05-17 06:57 UTC, gilesgas commented
OK @tomowatt and @pzeballos ,

To get this PR merged in a reasonable timeframe (and while my mind is fresh on this topic), I've pushed some wording updates directly to this PR.

Could please review these wording updates and let me know if they're accurate or not?
If they're incorrect, please let me know and how to fix the wording to make it correct.

If you don't have time to do this, then please let me know:

- Are _concurrency groups_ and _concurrency gates_ the same thing?
- If not, are _concurrency gates_ a specific implementation of _concurrency groups_?

2024-05-19 23:50 UTC, gilesgas requested changes
I need answers to the queries in my previous comment before approving this PR.

2024-06-03 18:10 UTC, pzeballos commented
> * Are _concurrency groups_ and _concurrency gates_ the same thing?
Kind of
> * If not, are _concurrency gates_ a specific implementation of _concurrency groups_?
Correct. Concurrency gates is a concept that you use, for example, to lock deployment either to an environment, or to end-to-end tests and the way to do it is with concurrency groups.
It's particularly useful for managing resources, ensuring that certain critical paths in your pipeline do not overwhelm shared resources, and preventing race condition

2025-04-04 15:55 UTC, pzeballos commented
@gilesgas any update on this one?

2025-04-11 20:40 UTC, closed without merging

2025-04-11 20:40 UTC, petetomasik commented
Closing in favor of https://github.com/buildkite/docs-private/pull/360