This small change ensures all dependencies used are installed
buildkite/docs pull request #2921
Opened 2024-08-02 00:52 UTC by wolfeidau

2024-08-02 01:20 UTC, mbelton-buildkite commented
Hey @wolfeidau, thanks for spotting this and contributing an update to make the flow smoother for customers. It looks like you've updated the command in the old v2 agent pages rather than the v3 agent pages. Was this meant to be an update for the v3 page?

It might also be worth updating the text that leads into the command to explain the context you added in this PR. :)

2024-08-07 03:42 UTC, gilesgas commented
Hi @wolfeidau ,

Following on from @mbelton-buildkite 's comment above (and sorry for my delayed reply as I only got back after a few weeks of holiday), did you mean to implement this update on this page instead?

https://github.com/buildkite/docs/blob/main/pages/agent/v3/debian.md

2024-08-07 03:43 UTC, gilesgas requested changes
Hi @wolfeidau ,

Following on from @mbelton-buildkite 's comment above (and sorry for my delayed reply as I only got back after a few weeks of holiday), did you mean to implement this update on this page instead?

https://github.com/buildkite/docs/blob/main/pages/agent/v3/debian.md

2024-08-09 06:04 UTC, wolfeidau commented
@gilesgas I did 😅 will sort it out now.

2024-08-09 06:09 UTC, wolfeidau commented
@gilesgas this is now rebased and correctly updating the v3 page.

2024-08-11 23:22 UTC, gilesgas approved these changes
Thanks @wolfeidau !

2024-08-11 23:22 UTC, merged