This endpoint creates webhook for pipeline using GitHub
buildkite/docs pull request #945
Opened 2021-02-25 23:15 UTC by JuanitoFatas

2021-02-25 23:53 UTC, blaknite commented on pages/apis/rest_api/pipelines.md.erb
> +Create SCM webhook for an existing pipeline using GitHub.
```suggestion
Create an SCM webhook for an existing pipeline. Currently supports pipelines configured using our GitHub App.
```

2021-02-26 00:06 UTC, blaknite approved these changes

2021-02-26 00:09 UTC, yob reviewed
neat, the extra detail will be useful!

I reckon it's worth waiting for @plaindocs docs to take a look too, just in case there's additional feedback he has.

2021-02-26 11:02 UTC, plaindocs requested changes
I think that with this change we can push it out.  

One other possiblity would be to change the title to mention GitHub, as it is the only option.

2021-03-01 09:02 UTC, plaindocs approved these changes

2021-03-01 09:04 UTC, plaindocs commented on pages/apis/rest_api/pipelines.md.erb
> +Create an Githook webhook for an existing pipeline that is configured using our GitHub App. Pushes to the linked GitHub repository will trigger builds.
Pretty sure I meant to write GitHub here. :man_facepalming:  

```suggestion
Create an GitHub webhook for an existing pipeline that is configured using our GitHub App. Pushes to the linked GitHub repository will trigger builds.
```

2021-03-01 09:13 UTC, merged